apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-frontend
  description: Node.js website linked to a catalog backend API
  tags:
    - nodejs
    - website
    - golden-path
    - jenkins
    - helm
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: url:https://github.com/rmallam/demo-frontend/tree/main/
    backstage.io/view-url: https://github.com/rmallam/demo-frontend
    backstage.io/edit-url: https://github.com/rmallam/demo-frontend/edit/main/catalog-info.yaml
    github.com/project-slug: rmallam/demo-frontend
    jenkins.io/job-full-name: demo/demo-frontend
    sonarqube.org/project-key: demo-frontend
    argocd/app-name: demo-frontend
    argocd/app-namespace: openshift-gitops
    backstage.io/kubernetes-id: demo-frontend
    backstage.io/kubernetes-namespace: demo-dev
    vault.io/secrets-path: rhdh
    jira/project-key: DEMO
    jira/component: demo-frontend
    snyk.io/org-id: stub-org
    snyk.io/org-name: stub-org
    snyk.io/project-ids: stub
    servicenow.com/entity-id: demo
    jfrog-artifactory/image-name: demo-frontend
    dynatrace.com/dynatrace-entity-id: SERVICE-DEMO
    acme.io/devfile-path: devfile.yaml
    acme.io/helm-chart: chart
    acme.io/mesh: ambient
    acme.io/mesh-ingress: gateway
    acme.io/devspaces-url: https://devspaces.apps.rosa.rosa-89s85.bhg0.p3.openshiftapps.com
    acme.io/devspaces-factory-url: https://devspaces.apps.rosa.rosa-89s85.bhg0.p3.openshiftapps.com#https://github.com/rmallam/demo-frontend?new&devfilePath=devfile.yaml
  links:
    - url: https://github.com/rmallam/demo-frontend/tree/main/chart
      title: Helm chart
      icon: github
    - url: https://github.com/rmallam/demo-frontend/blob/main/Jenkinsfile
      title: Jenkinsfile
      icon: github
    - url: https://jenkins-jenkins.apps.rosa.rosa-89s85.bhg0.p3.openshiftapps.com/job/demo/job/demo-frontend/
      title: Jenkins CI
      icon: dashboard
spec:
  type: website
  lifecycle: experimental
  owner: user:default/guest
  system: acme-demo
  dependsOn:
    - component:default/demo-backend
  consumesApis:
    - api:default/demo-backend-api
