apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    {{- if and .Values.mesh.enabled .Values.mesh.waypoint.enabled }}
    istio.io/use-waypoint: {{ include "app.waypointName" . }}
    {{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "app.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
