{{- if and .Values.mesh.enabled .Values.mesh.waypoint.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "app.waypointName" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    istio.io/waypoint-for: service
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  gatewayClassName: istio-waypoint
  listeners:
    - name: mesh
      port: 15008
      protocol: HBONE
{{- end }}
